In [1]:
import pandas as pd

#url = "http://samplecsvs.s3.amazonaws.com/SalesJan2009.csv"
#df = pd.read_csv(url)

url_path = 'http://www.anac.gov.br/assuntos/dados-e-estatisticas/percentuais-de-atrasos-e-cancelamentos-2/2018/'
url_files = ['vra-01_2018.csv',
             'vra-02_2018.csv',
             'vra_032018.csv',
             'vra_04.csv',
             'vra_05.csv',
             'vra_062018.csv',
             'vra_072018.csv',
             'vra_082018.csv',
             'vra_092018.csv']

df = pd.DataFrame()

for url_file in url_files: 
    print(url_file)
    url = url_path + url_file
    df_append = pd.read_csv(url, encoding='iso-8859-1', delimiter=';')
    df = df.append(df_append)

df.to_csv('voos.csv')

print(df.shape)
df.head()

vra-01_2018.csv
vra-02_2018.csv
vra_032018.csv
vra_04.csv
vra_05.csv
vra_062018.csv
vra_072018.csv

C:\Users\Diogo\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

vra_082018.csv
vra_092018.csv
(783256, 12)

,ICAO Empresa Aérea,Número Voo,Código Autorização (DI),Código Tipo Linha,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Chegada Prevista,Chegada Real,Situação Voo,Código Justificativa
0,AAL,1265,0,I,KMIA,SBEG,01/01/2018 20:30,01/01/2018 20:30,02/01/2018 01:53,02/01/2018 01:53,REALIZADO,NaN
1,AAL,1265,0,I,KMIA,SBEG,02/01/2018 20:30,02/01/2018 20:30,03/01/2018 01:53,03/01/2018 01:53,REALIZADO,NaN
2,AAL,1265,0,I,KMIA,SBEG,03/01/2018 20:30,03/01/2018 20:30,04/01/2018 01:53,04/01/2018 01:53,REALIZADO,NaN
3,AAL,1265,0,I,KMIA,SBEG,04/01/2018 20:30,04/01/2018 20:30,05/01/2018 01:53,05/01/2018 01:53,REALIZADO,NaN
4,AAL,1265,0,I,KMIA,SBEG,05/01/2018 20:30,05/01/2018 20:30,06/01/2018 01:53,06/01/2018 01:53,REALIZADO,NaN

In [2]:
df.tail()

,ICAO Empresa Aérea,Número Voo,Código Autorização (DI),Código Tipo Linha,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Chegada Prevista,Chegada Real,Situação Voo,Código Justificativa
80914,UPS,417,0,G,SBKP,SKBO,25/09/2018 00:20,25/09/2018 00:20,25/09/2018 05:55,25/09/2018 05:55,REALIZADO,NaN
80915,UPS,417,0,G,SKBO,KMIA,04/09/2018 07:10,04/09/2018 07:10,04/09/2018 10:40,04/09/2018 10:40,REALIZADO,NaN
80916,UPS,417,0,G,SKBO,KMIA,11/09/2018 07:10,11/09/2018 08:09,11/09/2018 10:40,11/09/2018 11:59,REALIZADO,RA
80917,UPS,417,0,G,SKBO,KMIA,18/09/2018 07:10,18/09/2018 07:10,18/09/2018 10:40,18/09/2018 10:40,REALIZADO,NaN
80918,UPS,417,0,G,SKBO,KMIA,25/09/2018 07:10,25/09/2018 07:10,25/09/2018 10:40,25/09/2018 10:40,REALIZADO,NaN